"""empty message

Revision ID: 9f68f5bfd5d0
Revises: 8a9658db170b
Create Date: 2022-03-09 20:21:14.410139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f68f5bfd5d0'
down_revision = '8a9658db170b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coll', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.add_column('comment', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.add_column('file', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.add_column('message', sa.Column('timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'timestamp')
    op.drop_column('file', 'timestamp')
    op.drop_column('comment', 'timestamp')
    op.drop_column('coll', 'timestamp')
    # ### end Alembic commands ###
