"""empty message

Revision ID: a65956defbd8
Revises: a577890c446e
Create Date: 2022-03-06 21:08:06.536445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a65956defbd8'
down_revision = 'a577890c446e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'tag', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tag', type_='foreignkey')
    op.drop_column('tag', 'user_id')
    # ### end Alembic commands ###
