"""empty message

Revision ID: d8e91af2abf3
Revises: 9f68f5bfd5d0
Create Date: 2022-03-09 21:17:07.421953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8e91af2abf3'
down_revision = '9f68f5bfd5d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('portrait', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'portrait')
    # ### end Alembic commands ###
