"""empty message

Revision ID: f4cba73cf4f4
Revises: add98ca63cc5
Create Date: 2022-02-24 22:00:56.771712

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f4cba73cf4f4'
down_revision = 'add98ca63cc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', mysql.VARCHAR(length=30), nullable=False))
    # ### end Alembic commands ###
